onLogin handler for providing proxy credentials to net request
arantes555/electron-fetch pull request #44
Opened 2022-02-14 08:06 UTC by ttrepka

This is another attempt at https://github.com/arantes555/electron-fetch/issues/9, an improved version of the long-open PR https://github.com/arantes555/electron-fetch/pull/10.

I added an `onLogin` option, which can be used for acquiring proxy credentials in an async manner (e.g. prompting the user), similarly to using `app.on('login')` in the renderer process.

2022-02-28 12:25 UTC, arantes555 commented
@ttrepka sorry for the delay, I was on holidays ! I'll try getting around to this this week

2022-03-16 17:12 UTC, arantes555 requested changes
The code itself looks pretty much ready to merge (with the exception of the handling of rejects). The main point which needs a bit of cleanup is the README.

2022-03-16 17:12 UTC, arantes555 commented on README.md
> +	onLogin: undefined // When running on Electron behind an authenticated HTTP proxy, handler of electron.ClientRequest's login event. Can be used for acquiring proxy credentials in an async manner (e.
Actually, my suggestion seems to be incorrect.

I suggest adding a code-block example of how to use it, something like:

```js
fetch(url, {
  onLogin (authInfo) { // this 'authInfo' is the one received by the 'login' event. See https://www.electronjs.org/docs/latest/api/client-request#event-login
    return Promise.resolve({ username: 'testuser', password: 'testpassword' })
  }
}))
```

2022-03-16 17:13 UTC, arantes555 commented on src/index.js
> +              callback()
Actually, this seems coherent.

2022-03-21 16:34 UTC, arantes555 commented
All looks good to me, but it seems tests fail on electron@6 with the error:
```
  1) electron-fetch: electron
       "after each" hook: Clear authenticated proxy session auth cache for "should return a promise":
     Error: Must specify options object
      at Session.<anonymous> (node_modules/electron/dist/resources/electron.asar/common/api/deprecate.js:114:32)
      at Session.clearAuthCache (node_modules/electron/dist/resources/electron.asar/browser/api/session.js:33:27)
      at Context.<anonymous> (test/test.js:2076:39)
```

2022-03-21 16:59 UTC, ttrepka commented
> All looks good to me, but it seems tests fail on electron@6 with the error:
> 
> ```
>   1) electron-fetch: electron
>        "after each" hook: Clear authenticated proxy session auth cache for "should return a promise":
>      Error: Must specify options object
>       at Session.<anonymous> (node_modules/electron/dist/resources/electron.asar/common/api/deprecate.js:114:32)
>       at Session.clearAuthCache (node_modules/electron/dist/resources/electron.asar/browser/api/session.js:33:27)
>       at Context.<anonymous> (test/test.js:2076:39)
> ```

Very strange. According to the docs, `clearAuthCache` should work without options https://github.com/electron/electron/blob/6-0-x/docs/api/session.md#sesclearauthcache. However, it throws the error "Must specify options object".
The only fix that worked for me is actually specifying the options. A problem with that is that it clutters the console with deprecation warnings ¯\\_(ツ)_/¯

2022-03-21 21:32 UTC, merged

2022-03-21 22:05 UTC, arantes555 commented
Great job! This is now merged.

I'll do some cleanup & dependency updating tomorrow and release a new version with this feature :)

2022-03-22 09:44 UTC, arantes555 commented
Published in electron-fetch@1.8.0